// City Names Library - Comprehensive list of Indian cities
// This library contains major cities from all states and union territories of India

export const cityNames = [
  // Major Metropolitan Cities
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Chennai",
  "Kolkata",
  "Pune",
  "Ahmedabad",
  "Jaipur",
  "Surat",
  "Lucknow",
  "Kanpur",
  "Nagpur",
  "Indore",
  "Thane",
  "Bhopal",
  "Visakhapatnam",
  "Pimpri-Chinchwad",
  "Patna",
  "Vadodara",
  "Ghaziabad",
  "Ludhiana",
  "Agra",
  "Nashik",
  "Faridabad",
  "Meerut",
  "Rajkot",
  "Kalyan-Dombivali",
  "Vasai-Virar",
  "Varanasi",
  "Srinagar",
  "Aurangabad",
  "Dhanbad",
  "Amritsar",
  "Allahabad",
  "Ranchi",
  "Howrah",
  "Coimbatore",
  "Jabalpur",
  "Gwalior",
  "Vijayawada",
  "Jodhpur",
  "Madurai",
  "Raipur",
  "Kota",
  "Guwahati",
  "Chandigarh",
  "Solapur",
  "Hubli-Dharwad",
  "Bareilly",
  "Moradabad",
  "Mysore",
  "Gurgaon",
  "Aligarh",
  "Jalandhar",
  "Tiruchirappalli",
  "Bhubaneswar",
  "Salem",
  "Warangal",
  "Mira-Bhayandar",
  "Thiruvananthapuram",
  "Bhiwandi",
  "Saharanpur",
  "Guntur",
  "Amravati",
  "Bikaner",
  "Noida",
  "Jamshedpur",
  "Bhilai",
  "Cuttack",
  "Firozabad",
  "Kochi",
  "Nellore",
  "Bhavnagar",
  "Dehradun",
  "Durgapur",
  "Asansol",
  "Rourkela",
  "Nanded",
  "Kolhapur",
  "Ajmer",
  "Akola",
  "Gulbarga",
  "Jamnagar",
  "Ujjain",
  "Loni",
  "Siliguri",
  "Jhansi",
  "Ulhasnagar",
  "Jammu",
  "Sangli-Miraj",
  "Mangalore",
  "Erode",
  "Belgaum",
  "Ambattur",
  "Tirunelveli",
  "Malegaon",
  "Gaya",
  "Jalgaon",
  "Udaipur",
  "Maheshtala",
  "Tirupur",
  "Davanagere",
  "Kozhikode",
  "Akbarpur",
  "Kurnool",
  "Bokaro Steel City",
  "Rajpur Sonarpur",
  "South Dumdum",
  "Bellary",
  "Patiala",
  "Gopalpur",
  "Agartala",
  "Bhagalpur",
  "Muzaffarnagar",
  "Bhatpara",
  "Panihati",
  "Latur",
  "Dhule",
  "Rohtak",
  "Korba",
  "Bhilwara",
  "Brahmapur",
  "Muzaffarpur",
  "Ahmednagar",
  "Mathura",
  "Kollam",
  "Avadi",
  "Kadapa",
  "Kamarhati",
  "Bilaspur",
  "Shahjahanpur",
  "Satara",
  "Bijapur",
  "Rampur",
  "Shivamogga",
  "Chandrapur",
  "Junagadh",
  "Thrissur",
  "Alwar",
  "Bardhaman",
  "Kulti",
  "Kakinada",
  "Nizamabad",
  "Parbhani",
  "Tumkur",
  "Hisar",
  "Ozhukarai",
  "Bihar Sharif",
  "Panipat",
  "Darbhanga",
  "Bally",
  "Aizawl",
  "Dewas",
  "Ichalkaranji",
  "Karnal",
  "Bathinda",
  "Jalna",
  "Eluru",
  "Barasat",
  "Kirari Suleman Nagar",
  "Purnia",
  "Satna",
  "Mau",
  "Sonipat",
  "Farrukhabad",
  "Sagar",
  "Rourkela",
  "Durg",
  "Imphal",
  "Ratlam",
  "Hapur",
  "Arcot",
  "Anantapur",
  "Karimnagar",
  "Etawah",
  "Ambernath",
  "North Dumdum",
  "Bharatpur",
  "Begusarai",
  "New Delhi",
  "Gandhidham",
  "Baranagar",
  "Tiruvottiyur",
  "Puducherry",
  "Sikar",
  "Thoothukkudi",
  "Rewa",
  "Mirzapur",
  "Raichur",
  "Pali",
  "Ramagundam",
  "Haridwar",
  "Vijayanagaram",
  "Katihar",
  "Nagercoil",
  "Sri Ganganagar",
  "Karawal Nagar",
  "Mango",
  "Thanjavur",
  "Bulandshahr",
  "Uluberia",
  "Katni",
  "Sambhal",
  "Singrauli",
  "Nadiad",
  "Secunderabad",
  "Naihati",
  "Yamunanagar",
  "Bidhan Nagar",
  "Pallavaram",
  "Bidar",
  "Munger",
  "Panchkula",
  "Burhanpur",
  "Raurkela Industrial Township",
  "Kharagpur",
  "Dindigul",
  "Gandhinagar",
  "Hospet",
  "Nangloi Jat",
  "Malda",
  "Ongole",
  "Deoghar",
  "Chapra",
  "Haldia",
  "Khandwa",
  "Nandyal",
  "Morena",
  "Amroha",
  "Anand",
  "Bhind",
  "Bhalswa Jahangir Pur",
  "Madhyamgram",
  "Bhiwani",
  "Navsari",
  "Bahraich",
  "Meerut Cantonment",
  "Phagwara",
  "Port Blair",
  "Alappuzha",
  "Bhusawal",
  "Ratnagiri",
  "Shahdol",
  "Mahbubnagar",
  "Adoni",
  "Udupi",
  "Tenali",
  "Proddatur",
  "Saharsa",
  "Kavali",
  "Gorakhpur",
  "Chittoor",
  "Hazaribagh",
  "Bhimavaram",
  "Mandsaur",
  "Dibrugarh",
  "Kolar",
  "Bankura",
  "Mandya",
  "Dehri",
  "Vellore",
  "Sangli",
  "Tinsukia",
  "Guntakal",
  "Srikakulam",
  "Motihari",
  "Dharni",
  "Medinipur",
  "Bhadrak",
  "Siwan",
  "Bhusawal",
  "Ratnagiri",
  "Shahdol",
  "Mahbubnagar",
  "Adoni",
  "Udupi",
  "Tenali",
  "Proddatur",
  "Saharsa",
  "Kavali",
  "Gorakhpur",
  "Chittoor",
  "Hazaribagh",
  "Bhimavaram",
  "Mandsaur",
  "Dibrugarh",
  "Kolar",
  "Bankura",
  "Mandya",
  "Dehri",
  "Vellore",
  "Sangli",
  "Tinsukia",
  "Guntakal",
  "Srikakulam",
  "Motihari",
  "Dharni",
  "Medinipur",
  "Bhadrak",
  "Siwan"
];

// Function to get all cities
export const getAllCities = () => {
  return [...cityNames];
};

// Function to get cities by state (basic mapping)
export const getCitiesByState = (state) => {
  const stateCityMap = {
    "Maharashtra": ["Mumbai", "Pune", "Nagpur", "Thane", "Nashik", "Aurangabad", "Solapur", "Kolhapur", "Nanded", "Akola", "Latur", "Dhule", "Ahmednagar", "Satara", "Chandrapur", "Parbhani", "Tumkur", "Jalna", "Ambernath", "Bhusawal", "Ratnagiri", "Mandsaur", "Sangli", "Bhimavaram", "Medinipur"],
    "Delhi": ["Delhi", "New Delhi", "North Dumdum", "South Dumdum"],
    "Karnataka": ["Bangalore", "Mysore", "Hubli-Dharwad", "Gulbarga", "Mangalore", "Belgaum", "Davanagere", "Bellary", "Shivamogga", "Tumkur", "Bidar", "Raichur", "Hospet", "Mandya", "Kolar", "Udupi", "Tenali", "Kavali", "Chittoor", "Bhimavaram"],
    "Telangana": ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Ramagundam", "Secunderabad", "Adoni", "Mahbubnagar", "Srikakulam"],
    "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Salem", "Tiruchirappalli", "Vellore", "Thiruvananthapuram", "Erode", "Tirunelveli", "Tirupur", "Avadi", "Kadapa", "Nellore", "Tiruvottiyur", "Thoothukkudi", "Nagercoil", "Thanjavur", "Pallavaram", "Dindigul", "Nandyal", "Proddatur", "Tenali"],
    "West Bengal": ["Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri", "Bardhaman", "Bally", "Barasat", "North Dumdum", "South Dumdum", "Bidhan Nagar", "Kharagpur", "Malda", "Haldia", "Medinipur", "Bankura", "Bhadrak"],
    "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Gandhidham", "Anand", "Navsari", "Bhimavaram"],
    "Uttar Pradesh": ["Lucknow", "Kanpur", "Agra", "Varanasi", "Allahabad", "Bareilly", "Moradabad", "Aligarh", "Saharanpur", "Firozabad", "Jhansi", "Gaya", "Muzaffarnagar", "Bhatpara", "Panihati", "Shahjahanpur", "Rampur", "Hisar", "Panipat", "Sonipat", "Farrukhabad", "Etawah", "Mirzapur", "Bulandshahr", "Katni", "Sambhal", "Singrauli", "Amroha", "Bhind", "Bahraich", "Gorakhpur", "Dehri", "Motihari", "Siwan"],
    "Rajasthan": ["Jaipur", "Jodhpur", "Kota", "Bikaner", "Ajmer", "Udaipur", "Bhilwara", "Alwar", "Sikar", "Sri Ganganagar", "Bharatpur", "Pali", "Bhiwani", "Phagwara", "Karnal", "Bathinda", "Ratlam", "Hapur", "Rewa", "Sagar", "Dewas", "Mandsaur"],
    "Madhya Pradesh": ["Indore", "Bhopal", "Gwalior", "Jabalpur", "Ujjain", "Dewas", "Ratlam", "Sagar", "Durg", "Bhind", "Katni", "Sambhal", "Singrauli", "Amroha", "Mandsaur", "Hazaribagh", "Dehri"],
    "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool", "Kakinada", "Anantapur", "Karimnagar", "Vijayanagaram", "Nandyal", "Guntakal", "Srikakulam", "Tenali", "Proddatur", "Kavali", "Chittoor", "Bhimavaram"],
    "Kerala": ["Kochi", "Thiruvananthapuram", "Kozhikode", "Kollam", "Thrissur", "Alappuzha", "Udupi", "Tenali"],
    "Punjab": ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Phagwara", "Karnal", "Sri Ganganagar", "Bhiwani"],
    "Bihar": ["Patna", "Dhanbad", "Gaya", "Muzaffarpur", "Bhagalpur", "Katihar", "Begusarai", "Purnia", "Saharsa", "Chapra", "Motihari", "Siwan"],
    "Odisha": ["Bhubaneswar", "Cuttack", "Rourkela", "Brahmapur", "Sambalpur", "Bhadrak", "Medinipur"],
    "Assam": ["Guwahati", "Dibrugarh", "Siliguri", "Tinsukia"],
    "Jharkhand": ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro Steel City", "Dhanbad", "Hazaribagh", "Dehri"],
    "Chhattisgarh": ["Raipur", "Bhilai", "Durg", "Bilaspur", "Korba", "Raichur"],
    "Haryana": ["Faridabad", "Gurgaon", "Panchkula", "Yamunanagar", "Panipat", "Sonipat", "Karnal", "Bhiwani", "Hisar", "Rohtak"],
    "Uttarakhand": ["Dehradun", "Haridwar"],
    "Jammu and Kashmir": ["Srinagar", "Jammu"],
    "Himachal Pradesh": ["Shimla"],
    "Tripura": ["Agartala"],
    "Manipur": ["Imphal"],
    "Mizoram": ["Aizawl"],
    "Meghalaya": ["Shillong"],
    "Nagaland": ["Kohima"],
    "Arunachal Pradesh": ["Itanagar"],
    "Sikkim": ["Gangtok"],
    "Goa": ["Panaji"],
    "Chandigarh": ["Chandigarh"],
    "Puducherry": ["Puducherry"],
    "Andaman and Nicobar": ["Port Blair"],
    "Dadra and Nagar Haveli": ["Silvassa"],
    "Daman and Diu": ["Daman"],
    "Lakshadweep": ["Kavaratti"]
  };
  
  return stateCityMap[state] || [];
};

// Function to search cities by name
export const searchCities = (searchTerm) => {
  const term = searchTerm.toLowerCase();
  return cityNames.filter(city => 
    city.toLowerCase().includes(term)
  );
};

// Function to get cities starting with a specific letter
export const getCitiesByFirstLetter = (letter) => {
  const firstLetter = letter.toUpperCase();
  return cityNames.filter(city => 
    city.startsWith(firstLetter)
  );
};

// Function to get random cities
export const getRandomCities = (count = 5) => {
  const shuffled = [...cityNames].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
};

// Function to validate if a city exists
export const isValidCity = (cityName) => {
  return cityNames.includes(cityName);
};

// Export default for convenience
export default cityNames;
